# Generated by Django 5.2.1 on 2025-05-29 20:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_profile_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid email address', regex='^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$')]),
        ),
        migrations.AddField(
            model_name='employee',
            name='job_description',
            field=models.TextField(blank=True, help_text="Detailed description of employee's responsibilities", null=True),
        ),
    ]
